spring:
  application:
    name: spring-flyway
  datasource:
    url: jdbc:snowflake://${SNOWFLAKE_TEST_ACCOUNT}.snowflakecomputing.com?database=${SNOWFLAKE_TEST_DATABASE}&schema=${SNOWFLAKE_TEST_SCHEMA}&warehouse=${SNOWFLAKE_TEST_WAREHOUSE}&role=${SNOWFLAKE_TEST_ROLE}
    driverClassName: net.snowflake.client.jdbc.SnowflakeDriver
    username: ${SNOWFLAKE_TEST_USER}
    password: ${SNOWFLAKE_TEST_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: net.snowflake.hibernate.dialect.SnowflakeDialect
        format_sql: true
        dialect.snowflake.table_type: STANDARD
        dialect.snowflake.development_mode: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
